# Generated by Django 4.0.5 on 2022-06-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diag_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diag_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hosp_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateTimeField(null=True)),
                ('diag_code', models.CharField(max_length=10, null=True)),
                ('comment', models.TextField(null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient')),
            ],
        ),
    ]
