# Generated by Django 4.0.5 on 2022-06-05 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0002_patient_birth_date_patient_diag_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='reg_time',
            new_name='reg_date',
        ),
    ]
