# Generated by Django 4.0.5 on 2022-06-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0003_rename_reg_time_patient_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hosp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reg_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='note_date',
            field=models.DateField(null=True),
        ),
    ]
