# Generated by Django 4.0.5 on 2022-06-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0004_alter_patient_birth_date_alter_patient_hosp_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='patient',
            name='oper_date',
            field=models.DateField(null=True),
        ),
    ]
