# Generated by Django 4.1 on 2022-11-06 19:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_patient_parent_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id'], 'verbose_name': 'пациент', 'verbose_name_plural': 'пациенты'},
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='comission',
            field=models.BooleanField(default=False, verbose_name='Прошел комиссию'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='color',
            field=models.CharField(default='#808080', max_length=7, verbose_name='Мой цвет'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='adress',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diag_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код диагноза'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diag_desc',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Описание диагноза'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fio',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hosp_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата госпитализации'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='oper_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='oper_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон родителя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reg_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
