# Generated by Django 4.1 on 2022-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_patient_comission_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('OC', 'На комиссии'), ('PC', 'Прошел комиссию'), ('HF', 'Лечение приостановлено')], default='OC', max_length=2, verbose_name='Прошел комиссию'),
        ),
    ]
